name: tangaya_apps
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter 
  get: ^4.7.2
  weather: ^3.2.1
  flutter_svg: ^2.1.0
  skeletonizer: ^1.4.3
  intl: ^0.20.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/    
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800